"""
Django settings for proyecto1 project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Este archivo centraliza la configuracion general del proyecto Django:
# apps instaladas, base de datos, idioma, zona horaria y manejo de archivos.

# BASE_DIR apunta a la raiz del proyecto y sirve para construir rutas internas.
BASE_DIR = Path(__file__).resolve().parent.parent


# Clave interna usada por Django para funciones de seguridad.
# En produccion no debe exponerse en el codigo.
SECRET_KEY = 'django-insecure-zemx@@abk12@gfx3b63+pc^teyg^dmsa!pwlfa$f2+hl+_*k=^'

# DEBUG=True muestra errores detallados. Solo se usa en desarrollo.
DEBUG = True

# Lista de dominios permitidos cuando el proyecto se publique.
ALLOWED_HOSTS = []


# INSTALLED_APPS registra todo lo que Django debe cargar al iniciar.
# Aqui estan las apps internas de Django, la app del proyecto y DRF.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'products',
    'rest_framework',
]

# MIDDLEWARE define procesos que se ejecutan en cada peticion/respuesta.
# Por ejemplo: seguridad, sesiones, autenticacion y proteccion CSRF.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto1.urls'

# TEMPLATES configura como Django buscaria plantillas HTML.
# En este proyecto el enfoque principal es la API, pero Django deja esto listo.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto1.wsgi.application'


# DATABASES define la base de datos del proyecto.
# Se usa SQLite por simplicidad academica y porque no requiere instalacion aparte.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Estas reglas validan la seguridad de las contrasenas de los usuarios.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Configuracion regional del proyecto.
# Se ajusta a espanol de Colombia y a la zona horaria de Bogota.
LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# STATIC_URL define la ruta base de archivos estaticos.
STATIC_URL = 'static/'

# MEDIA_URL y MEDIA_ROOT sirven para guardar y exponer archivos subidos,
# como la imagen opcional de cada reporte de objeto.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Tipo de llave primaria por defecto para los modelos nuevos.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
