# Generated by Django 5.2.13 on 2026-04-21 01:30

from django.db import migrations, models


# Esta migracion adapta la app al proyecto real:
# crea ReporteObjeto y elimina el modelo anterior Product.
class Migration(migrations.Migration):

    # Esta migracion se ejecuta despues de la 0001.
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteObjeto',
            # Aqui se definen los campos iniciales del modelo de reportes.
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_objeto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('celular', 'Celular'), ('cuaderno', 'Cuaderno'), ('llaves', 'Llaves'), ('documentos', 'Documentos'), ('otros', 'Otros')], max_length=20)),
                ('lugar', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('entregado', 'Entregado')], max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportes/')),
            ],
        ),
        # Se elimina el modelo anterior porque ya no corresponde al proyecto.
        migrations.DeleteModel(
            name='Product',
        ),
    ]
