# Generated by Django 5.2.13 on 2026-04-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_reporteobjeto_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteobjeto',
            options={'ordering': ['-fecha_reporte'], 'verbose_name': 'reporte de objeto', 'verbose_name_plural': 'reportes de objetos'},
        ),
        migrations.AlterField(
            model_name='reporteobjeto',
            name='estado',
            field=models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('entregado', 'Entregado')], default='perdido', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporteobjeto',
            name='lugar',
            field=models.CharField(choices=[('bloque', 'Bloque'), ('salon', 'Salon'), ('biblioteca', 'Biblioteca'), ('cafeteria', 'Cafeteria'), ('otros', 'Otros espacios')], max_length=100),
        ),
    ]
