# Generated by Django 5.2.13 on 2026-05-19 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_reporteobjeto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteobjeto',
            options={'ordering': ['-creado_en'], 'verbose_name': 'reporte de objeto', 'verbose_name_plural': 'reportes de objetos'},
        ),
        migrations.RemoveField(
            model_name='reporteobjeto',
            name='fecha_reporte',
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='accion_objeto',
            field=models.CharField(choices=[('entrega_directa', 'Lo entregará directamente al dueño'), ('otro_lugar', 'Lo dejará en otro lugar')], default='otro_lugar', max_length=20),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='eliminado_vista_publica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='encontrado_contacto',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='encontrado_nombre',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='encontrado_tipo_persona',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrativo', 'Administrativo')], default='estudiante', max_length=20),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='fecha_eliminacion_publica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='fecha_evento',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='lugar_entrega',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='perdido_contacto',
            field=models.CharField(default='Pendiente por confirmar', max_length=140),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='perdido_nombre',
            field=models.CharField(default='Sin identificar', max_length=140),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='perdido_tipo_persona',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('administrativo', 'Administrativo')], default='estudiante', max_length=20),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='tipo_reporte',
            field=models.CharField(choices=[('perdido', 'Objeto perdido'), ('encontrado', 'Objeto encontrado')], default='perdido', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporteobjeto',
            name='categoria',
            field=models.CharField(choices=[('documentos', 'Documentos'), ('tecnologia', 'Tecnología'), ('llaves', 'Llaves'), ('ropa', 'Ropa'), ('cuadernos_libros', 'Cuadernos o libros'), ('otros', 'Otros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reporteobjeto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('entregado', 'Entregado'), ('por_confirmar', 'Por confirmar')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporteobjeto',
            name='lugar',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='reporteobjeto',
            name='nombre_objeto',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='CambioEstadoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('pendiente', 'Pendiente'), ('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('entregado', 'Entregado'), ('por_confirmar', 'Por confirmar')], max_length=20)),
                ('estado_solicitado', models.CharField(choices=[('pendiente', 'Pendiente'), ('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('entregado', 'Entregado'), ('por_confirmar', 'Por confirmar')], max_length=20)),
                ('solicitado_por', models.CharField(default='usuario', max_length=80)),
                ('aprobacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_pendientes', to='products.reporteobjeto')),
            ],
            options={
                'verbose_name': 'cambio de estado pendiente',
                'verbose_name_plural': 'cambios de estado pendientes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(max_length=100)),
                ('rol', models.CharField(default='usuario', max_length=40)),
                ('campo', models.CharField(max_length=80)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('aprobacion', models.CharField(choices=[('no_aplica', 'No aplica'), ('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='no_aplica', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='products.reporteobjeto')),
            ],
            options={
                'verbose_name': 'historial de cambio',
                'verbose_name_plural': 'historial de cambios',
                'ordering': ['-creado_en'],
            },
        ),
    ]
