# Generated by Django 5.2.13 on 2026-05-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_reporteobjeto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteobjeto',
            name='prioridad',
        ),
    ]
