# Generated by Django 5.2.13 on 2026-05-25 20:44

import django.db.models.deletion
from django.db import migrations, models


def completar_reportes_existentes(apps, schema_editor):
    ReporteObjeto = apps.get_model('products', 'ReporteObjeto')

    for reporte in ReporteObjeto.objects.all().order_by('pk'):
        if not reporte.codigo:
            reporte.codigo = f'REP-{reporte.creado_en.year}-{reporte.pk:06d}'

        if reporte.tipo_reporte == 'encontrado':
            reporte.reportante_nombre = reporte.reportante_nombre or reporte.encontrado_nombre or 'Persona que encontró el objeto'
            reporte.reportante_correo = reporte.reportante_correo or _correo_o_pendiente(reporte.encontrado_contacto)
            reporte.perdido_nombre = reporte.perdido_nombre or 'Sin identificar'
            reporte.perdido_contacto = reporte.perdido_contacto or 'Pendiente por confirmar'
        else:
            reporte.reportante_nombre = reporte.reportante_nombre or reporte.perdido_nombre or 'Persona que perdió el objeto'
            reporte.reportante_correo = reporte.reportante_correo or _correo_o_pendiente(reporte.perdido_contacto)

        reporte.save(update_fields=[
            'codigo',
            'reportante_nombre',
            'reportante_correo',
            'perdido_nombre',
            'perdido_contacto',
        ])


def _correo_o_pendiente(valor):
    return valor if valor and '@' in valor else 'pendiente@example.com'


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_reporteobjeto_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcambio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historialcambio',
            name='usuario_admin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='reportante_celular',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='reportante_correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='reportante_nombre',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.CreateModel(
            name='CoincidenciaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField(default=0)),
                ('motivos', models.CharField(blank=True, max_length=255)),
                ('notificada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reporte_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias_generadas', to='products.reporteobjeto')),
                ('reporte_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias_recibidas', to='products.reporteobjeto')),
            ],
            options={
                'verbose_name': 'coincidencia de reporte',
                'verbose_name_plural': 'coincidencias de reportes',
                'ordering': ['-creado_en'],
                'unique_together': {('reporte_origen', 'reporte_relacionado')},
            },
        ),
        migrations.RunPython(completar_reportes_existentes, migrations.RunPython.noop),
    ]
