# Generated by Django 5.2.13 on 2026-05-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_historialcambio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteobjeto',
            name='reportante_correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reporteobjeto',
            name='reportante_nombre',
            field=models.CharField(max_length=140),
        ),
    ]
