# Generated by Django 5.2.13 on 2026-05-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_reporteobjeto_reportante_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteobjeto',
            name='fecha_validacion_admin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporteobjeto',
            name='validado_por_admin',
            field=models.BooleanField(default=False),
        ),
    ]
